version: 2
    
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: lsagentrelay
    package_name: "lsagentrelay"
    description: "Lansweeper Agent Relay/Proxy"
    vendor: "Cloudyne Systems"
    maintainer: Cloudyne Systems <support@cloudyne.org>
    file_name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    formats:
      - deb
      - apk
      - rpm
    bindir: /usr/local/bin

dockers:
  - image_templates:
    - clysec/lsagentrelay:{{ .Tag }}
    - clysec/lsagentrelay:latest
    - ghcr.io/clysec/lsagentrelay:{{ .Tag }}
    - ghcr.io/clysec/lsagentrelay:latest
